Environment:
  WaterSurfaceZ: 0
  KinematicViscosity: 1.35e-06
  SeaTemperature: 10
  ReynoldsNumberCalculation: Flow direction
  HorizontalWaterDensityFactor: ~
  VerticalDensityVariation: Constant
  SeabedType: Flat
  SeabedOrigin:
  - 0
  - 0
  NominalDepth: ~
  SeabedSlopeDirection: 0
  SeabedModel: Elastic
  WaveKinematicsCutoffDepth: Infinity
  WaveCalculationMethod: Instantaneous position (exact)
  WaveCalculationTimeInterval: 0
  WaveCalculationSpatialInterval: 0
  MultipleCurrentDataCanBeDefined: false
  CurrentModel: Variation scheme
  CurrentRamped: false
  CurrentApplyVerticalStretching: false
  HorizontalCurrentFactor: ~
  VerticalCurrentVariationMethod: Interpolated
  IncludeVesselWindLoads: true
  IncludeLineWindLoads: true
  IncludeBuoyWindLoads: true
  IncludeBuoyWingWindLoads: true
  WindRamping: From mean
  WindType: NPD spectrum
  AirDensity: 0.001225
  AirSpeedOfSound: 343
  VerticalWindVariationFactor: ~
  SeabedShearStiffness: 100.0
  SeabedNormalStiffness: 100.0
  KinematicStretchingMethod: Vertical stretching
  UserSpecifiedRandomWaveSeeds: false
  WaveFrequencySpectrumDiscretisationMethod: Equal energy
  SeabedSlope: 0.0
  WindTimeOrigin: 0
  WindSeed: 1796823655
  WindSpectrumFMax: 0.43
  WindSpectrumFMin: 0.0016666666666666668
  NumberOfWindComponents: 1000
  WindSpectrumElevation: 150
  Density: 1.025
  SeabedOriginDepth: 200.0
  WaveTrains:
  - Name: Wave1
    WaveType: JONSWAP
    WaveDirection: 180.0
    WaveOrigin:
    - 0
    - 0
    WaveTimeOrigin: 0
    WaveNumberOfSpectralDirections: 1
    WaveJONSWAPParameters: Partially specified
    WaveHs: 4.0
    WaveTz: 8.52552
    WaveGamma: 3.3
    WaveNumberOfComponents: 200
    WaveSpectrumMinRelFrequency: 0.5
    WaveSpectrumMaxRelFrequency: 10
    WaveSpectrumMaxComponentFrequencyRange: 0.05
  RefCurrentSpeed: 0.0
  RefCurrentDirection: 180.0
  CurrentDepth, CurrentFactor, CurrentRotation:
  - - 0.0
    - 1.0
    - 0
  - - 100.0
    - 1.0
    - 0
  WindSpeed: 17.1
  WindDirection: 180.0
