Environment:
  WaterSurfaceZ: 0
  KinematicViscosity: 15e-6
  SeaTemperature: 10
  ReynoldsNumberCalculation: Flow direction
  HorizontalWaterDensityFactor: ~
  VerticalDensityVariation: Constant
  SeabedType: Flat
  SeabedOrigin:
  - 0
  - 0
  NominalDepth: ~
  SeabedSlopeDirection: 0
  SeabedModel: Elastic
  WaveKinematicsCutoffDepth: Infinity
  WaveCalculationMethod: Instantaneous position (exact)
  WaveCalculationTimeInterval: 0
  WaveCalculationSpatialInterval: 0
  MultipleCurrentDataCanBeDefined: false
  CurrentModel: Variation scheme
  CurrentRamped: false
  CurrentApplyVerticalStretching: false
  HorizontalCurrentFactor: ~
  VerticalCurrentVariationMethod: Interpolated
  IncludeVesselWindLoads: true
  IncludeLineWindLoads: true
  IncludeBuoyWindLoads: true
  IncludeBuoyWingWindLoads: true
  WindRamping: From mean
  WindType: Constant
  AirDensity: 0.0799077895374654
  AirSpeedOfSound: 1125.3280839895012
  VerticalWindVariationFactor: ~
  SeabedSlope: 0.0
  SeabedNormalStiffness: 25.0
  SeabedShearStiffness: 3.5
  Density: 64.0
  SeabedOriginDepth: 2950.0
  WaveTrains:
  - Name: Wave
    WaveType: Dean stream
    WaveDirection: 180.0
    WaveHeight: 25.0
    WavePeriod: 18.0
    WaveOrigin:
    - 0
    - 0
    WaveTimeOrigin: 0
    WaveStreamFunctionOrder: 5
    WaveCurrentSpeedInWaveDirectionAtMeanWaterLevel: ~
  RefCurrentSpeed: 1.0
  RefCurrentDirection: 180.0
  CurrentDepth, CurrentFactor, CurrentRotation:
  - - 0.0
    - 3.6
    - 0
  - - 130.0
    - 3.4
    - 0
  - - 260.0
    - 3.0
    - 0
  - - 300.0
    - 1.9
    - 0
  - - 350.0
    - 1.0
    - 0
  - - 400.0
    - 0.65
    - 0
  - - 590.0
    - 0.4
    - 0
  - - 820.0
    - 0.33
    - 0
  - - 2854.0
    - 0.33
    - 0
  - - 2903.0
    - 0.32
    - 0
  - - 2935.0
    - 0.3
    - 0
  - - 2945.5
    - 0.13
    - 0
  - - 2950.0
    - 0.0
    - 0
  WindSpeed: 0.0
  WindDirection: 0.0
