Environment:
  WaterSurfaceZ: 0
  KinematicViscosity: 1.35e-06
  SeaTemperature: 10
  ReynoldsNumberCalculation: Flow direction
  HorizontalWaterDensityFactor: ~
  VerticalDensityVariation: Constant
  SeabedType: Flat
  SeabedOrigin:
  - 0
  - 0
  NominalDepth: ~
  SeabedSlopeDirection: 0
  SeabedModel: Elastic
  WaveKinematicsCutoffDepth: 30
  WaveCalculationMethod: Instantaneous position (exact)
  WaveCalculationTimeInterval: 0
  WaveCalculationSpatialInterval: 0
  MultipleCurrentDataCanBeDefined: false
  CurrentModel: Variation scheme
  CurrentRamped: false
  CurrentApplyVerticalStretching: false
  HorizontalCurrentFactor: ~
  VerticalCurrentVariationMethod: Interpolated
  IncludeVesselWindLoads: true
  IncludeLineWindLoads: true
  IncludeBuoyWindLoads: true
  IncludeBuoyWingWindLoads: true
  WindRamping: Unramped
  WindType: Full field
  AirDensity: 0.001225
  AirSpeedOfSound: 343
  VerticalWindVariationFactor: ~
  SeabedSlope: 0.0
  WaveFrequencySpectrumDiscretisationMethod: Equal energy
  SeabedShearStiffness: 100.0
  SeabedNormalStiffness: 0.0
  KinematicStretchingMethod: Vertical stretching
  UserSpecifiedRandomWaveSeeds: false
  Density: 1.025
  SeabedOriginDepth: 30.0
  WaveTrains:
  - Name: Wave1
    WaveType: JONSWAP
    WaveDirection: 180.0
    WaveOrigin:
    - 0
    - 0
    WaveTimeOrigin: 0
    WaveNumberOfSpectralDirections: 1
    WaveJONSWAPParameters: Automatic
    WaveHs: 5.0
    WaveTz: 6.51155
    WaveNumberOfComponents: 200
    WaveSpectrumMinRelFrequency: 0.5
    WaveSpectrumMaxRelFrequency: 10
    WaveSpectrumMaxComponentFrequencyRange: 0.05
  RefCurrentSpeed: 0.0
  RefCurrentDirection: 180.0
  CurrentDepth, CurrentFactor, CurrentRotation:
  - - 0.0
    - 1.0
    - 0
  - - 100.0
    - 1.0
    - 0
  WindSpeed: 0
  WindDirection: 180.0
