Environment:
  WaterSurfaceZ: 0
  KinematicViscosity: 1.35e-06
  SeaTemperature: 10
  ReynoldsNumberCalculation: Flow direction
  HorizontalWaterDensityFactor: ~
  VerticalDensityVariation: Constant
  Density: 1.025
  SeabedType: Flat
  SeabedOrigin:
  - 0
  - 0
  SeabedOriginDepth: 100.0
  NominalDepth: ~
  SeabedSlopeDirection: 180
  SeabedSlope: 0.0
  SeabedModel: Elastic
  SeabedNormalStiffness: 100.0
  SeabedShearStiffness: 100.0
  WaveTrains:
  - Name: Wave1
    WaveType: Dean stream
    WaveDirection: 90.0
    WaveHeight: 6.0
    WavePeriod: 7.0
    WaveOrigin:
    - 0
    - 0
    WaveTimeOrigin: 0
  WaveKinematicsCutoffDepth: Infinity
  WaveCalculationMethod: Instantaneous position (exact)
  WaveCalculationTimeInterval: 0
  WaveCalculationSpatialInterval: 0
  MultipleCurrentDataCanBeDefined: 'No'
  CurrentModel: Variation scheme
  CurrentRamped: 'No'
  CurrentApplyVerticalStretching: 'No'
  HorizontalCurrentFactor: ~
  VerticalCurrentVariationMethod: Interpolated
  RefCurrentSpeed: 0.7
  RefCurrentDirection: 180.0
  CurrentDepth, CurrentFactor, CurrentRotation:
  - - 0
    - 1.0
    - 0
  IncludeVesselWindLoads: 'Yes'
  IncludeLineWindLoads: 'Yes'
  IncludeBuoyWindLoads: 'Yes'
  IncludeBuoyWingWindLoads: 'Yes'
  WindRamping: From mean
  WindType: Constant
  AirDensity: 0.00128
  AirSpeedOfSound: 343
  WindSpeed: 0.0
  WindDirection: 0.0
  VerticalWindVariationFactor: ~
