Environment:
  WaterSurfaceZ: 0
  KinematicViscosity: 1.35e-06
  SeaTemperature: 10
  ReynoldsNumberCalculation: Flow direction
  HorizontalWaterDensityFactor: ~
  VerticalDensityVariation: Constant
  SeabedType: Flat
  SeabedOrigin:
  - 0
  - 0
  SeabedSlopeDirection: 0
  SeabedModel: Elastic
  WaveKinematicsCutoffDepth: Infinity
  WaveCalculationMethod: Instantaneous position (exact)
  WaveCalculationTimeInterval: 0
  WaveCalculationSpatialInterval: 0
  MultipleCurrentDataCanBeDefined: false
  CurrentModel: Variation scheme
  CurrentRamped: false
  CurrentApplyVerticalStretching: 'No'
  HorizontalCurrentFactor: ~
  VerticalCurrentVariationMethod: Power law
  IncludeVesselWindLoads: true
  IncludeLineWindLoads: true
  IncludeBuoyWindLoads: true
  IncludeBuoyWingWindLoads: true
  WindRamping: From mean
  WindType: Constant
  AirDensity: 0.00128
  AirSpeedOfSound: 343
  VerticalWindVariationFactor: ~
  WaterDepth: 80.0
  SeabedShearStiffness: 100.0
  KinematicStretchingMethod: Vertical stretching
  UserSpecifiedRandomWaveSeeds: false
  SeabedSlope: 0.0
  WaveFrequencySpectrumDiscretisationMethod: Equal energy
  SeabedNormalStiffness: 100.0
  Density: 1.025
  WaveTrains:
  - Name: Wave1
    WaveType: JONSWAP
    WaveDirection: 177.5
    WaveOrigin:
    - 0
    - 0
    WaveTimeOrigin: -190
    WaveNumberOfSpectralDirections: 1
    WaveJONSWAPParameters: Automatic
    WaveHs: 10.0
    WaveTz: 12.0
    WaveNumberOfComponents: 100
    WaveSpectrumMinRelFrequency: 0.5
    WaveSpectrumMaxRelFrequency: 10
    WaveSpectrumMaxComponentFrequencyRange: 0.05
  CurrentExponent: 7
  CurrentSpeedAtSurface: 0.7
  CurrentSpeedAtSeabed: 0
  RefCurrentDirection: 182.5
  WindSpeed: 0.0
  WindDirection: 0.0
