Environment:
  WaterSurfaceZ: 0
  KinematicViscosity: 15e-6
  SeaTemperature: 10
  ReynoldsNumberCalculation: Flow direction
  HorizontalWaterDensityFactor: ~
  VerticalDensityVariation: Constant
  SeabedType: Flat
  SeabedOrigin:
  - 0
  - 0
  SeabedSlopeDirection: 0
  SeabedModel: Elastic
  WaveKinematicsCutoffDepth: Infinity
  WaveCalculationMethod: Instantaneous position (exact)
  WaveCalculationTimeInterval: 0
  WaveCalculationSpatialInterval: 0
  MultipleCurrentDataCanBeDefined: false
  CurrentModel: Variation scheme
  CurrentRamped: false
  CurrentApplyVerticalStretching: 'No'
  HorizontalCurrentFactor: ~
  VerticalCurrentVariationMethod: Power law
  IncludeVesselWindLoads: true
  IncludeLineWindLoads: true
  IncludeBuoyWindLoads: true
  IncludeBuoyWingWindLoads: true
  WindRamping: From mean
  WindType: Constant
  AirDensity: 0.0799077895374652
  AirSpeedOfSound: 1125.3280839895012
  VerticalWindVariationFactor: ~
  SeabedSlope: 0.0
  SeabedNormalStiffness: 31.8294017713208
  SeabedShearStiffness: 1.59147008856604
  WaterDepth: 6560.0
  Density: 63.9886595905483
  WaveTrains:
  - Name: Wave1
    WaveType: Dean stream
    WaveDirection: 180.0
    WaveHeight: 25.0
    WavePeriod: 14.0
    WaveOrigin:
    - 0
    - 0
    WaveTimeOrigin: 0
    WaveStreamFunctionOrder: 5
    WaveCurrentSpeedInWaveDirectionAtMeanWaterLevel: ~
  CurrentExponent: 3
  CurrentSpeedAtSurface: 1.5
  CurrentSpeedAtSeabed: 0
  RefCurrentDirection: 180.0
  WindSpeed: 0.0
  WindDirection: 0.0
