Environment:
  WaterSurfaceZ: 0
  KinematicViscosity: 1.35e-06
  SeaTemperature: 10
  ReynoldsNumberCalculation: Flow direction
  HorizontalWaterDensityFactor: ~
  VerticalDensityVariation: Constant
  SeabedType: Flat
  SeabedOrigin:
  - 0
  - 0
  NominalDepth: ~
  SeabedSlopeDirection: 0
  SeabedModel: Elastic
  WaveKinematicsCutoffDepth: Infinity
  WaveCalculationMethod: Instantaneous position (exact)
  WaveCalculationTimeInterval: 0
  WaveCalculationSpatialInterval: 0
  MultipleCurrentDataCanBeDefined: false
  CurrentModel: Variation scheme
  CurrentRamped: false
  CurrentApplyVerticalStretching: false
  HorizontalCurrentFactor: ~
  VerticalCurrentVariationMethod: Interpolated
  IncludeVesselWindLoads: true
  IncludeLineWindLoads: true
  IncludeBuoyWindLoads: true
  IncludeBuoyWingWindLoads: true
  WindRamping: From mean
  WindType: Constant
  AirDensity: 0.00128
  AirSpeedOfSound: 343
  VerticalWindVariationFactor: ~
  SeabedNormalStiffness: 100.0
  SeabedSlope: 0.0
  KinematicStretchingMethod: Vertical stretching
  WaveFrequencySpectrumDiscretisationMethod: Equal energy
  UserSpecifiedRandomWaveSeeds: false
  SeabedShearStiffness: 100.0
  Density: 1.025
  SeabedOriginDepth: 100.0
  WaveTrains:
  - Name: Wave1
    WaveType: JONSWAP
    WaveDirection: 135.0
    WaveOrigin:
    - 0
    - 0
    WaveTimeOrigin: -10.5e3
    WaveNumberOfSpectralDirections: 1
    WaveJONSWAPParameters: Automatic
    WaveHs: 1.0
    WaveTz: 4.0
    WaveNumberOfComponents: 100
    WaveSpectrumMinRelFrequency: 0.5
    WaveSpectrumMaxRelFrequency: 10
    WaveSpectrumMaxComponentFrequencyRange: 0.05
  RefCurrentSpeed: 0.5
  RefCurrentDirection: 160.0
  CurrentDepth, CurrentFactor, CurrentRotation:
  - - 0.0
    - 1.0
    - 0
  - - 100.0
    - 1.0
    - 0
  WindSpeed: 0.0
  WindDirection: 0.0
