Environment:
  WaterSurfaceZ: 0
  KinematicViscosity: 1.35e-06
  SeaTemperature: 10
  ReynoldsNumberCalculation: Flow direction
  HorizontalWaterDensityFactor: ~
  VerticalDensityVariation: Constant
  Density: 1.03
  SeabedType: Flat
  SeabedOrigin:
  - 0
  - 0
  SeabedOriginDepth: 8.0
  NominalDepth: ~
  SeabedSlopeDirection: 180
  SeabedSlope: 0.57
  SeabedModel: Elastic
  SeabedNormalStiffness: 1000.0
  SeabedShearStiffness: 100.0
  WaveTrains:
  - Name: Wave1
    WaveType: Dean stream
    WaveDirection: 180.0
    WaveHeight: 0.0
    WavePeriod: 8.0
    WaveOrigin:
    - 0
    - 0
    WaveTimeOrigin: 0
    WaveStreamFunctionOrder: 5
    WaveCurrentSpeedInWaveDirectionAtMeanWaterLevel: ~
  WaveKinematicsCutoffDepth: Infinity
  WaveCalculationMethod: Instantaneous position (exact)
  WaveCalculationTimeInterval: 0
  WaveCalculationSpatialInterval: 0
  MultipleCurrentDataCanBeDefined: 'No'
  CurrentModel: Variation scheme
  CurrentRamped: 'No'
  CurrentApplyVerticalStretching: 'No'
  HorizontalCurrentFactor: ~
  VerticalCurrentVariationMethod: Interpolated
  RefCurrentSpeed: 1.0
  RefCurrentDirection: 270.0
  CurrentDepth, CurrentFactor, CurrentRotation:
  - - 0.0
    - 0.46
    - 0
  - - 6.0
    - 0.39
    - 0
  - - 15.0
    - 0.33
    - 0
  IncludeVesselWindLoads: 'Yes'
  IncludeLineWindLoads: 'Yes'
  IncludeBuoyWindLoads: 'Yes'
  IncludeBuoyWingWindLoads: 'Yes'
  WindRamping: From mean
  WindType: Constant
  AirDensity: 0.00128
  AirSpeedOfSound: 343
  WindSpeed: 8.87
  WindDirection: 270.0
  VerticalWindVariationFactor: ~
