default:
  log_level: DEBUG

analysis:
  forced_rerun: False
  seo:
    pyseoanalyzer: False
    seolib: True
    seoaudit: True
    advertools: False

url: https://www.orthodonticslimited.com/
alias: orthodonticslimited
competition: dental_practice

# urls:
#   - url: https://www.starplusdental.com/
#     alias: starplusdental
#     competition: dental_practice
#   - url: https://www.dentistsuwanee.com/
#     alias: dentistsuwanee
#     competition: dental_practice
# - url: https://www.orthodonticslimited.com/
#   alias: orthodonticslimited
#   competition: dental_practice

output_path: src\\drone\\results

service_account_id: vamseeachanta@digitalmarketing-372401.iam.gserviceaccount.com
