Environment:
  WaterSurfaceZ: 0
  KinematicViscosity: 1.35e-06
  SeaTemperature: 10
  ReynoldsNumberCalculation: Flow direction
  HorizontalWaterDensityFactor: ~
  VerticalDensityVariation: Constant
  SeabedType: Flat
  SeabedOrigin:
  - 0
  - 0
  NominalDepth: ~
  SeabedSlopeDirection: 0
  SeabedModel: Elastic
  WaveKinematicsCutoffDepth: Infinity
  WaveCalculationMethod: Instantaneous position (exact)
  WaveCalculationTimeInterval: 0
  WaveCalculationSpatialInterval: 0
  MultipleCurrentDataCanBeDefined: false
  CurrentModel: Variation scheme
  CurrentRamped: false
  CurrentApplyVerticalStretching: false
  HorizontalCurrentFactor: ~
  VerticalCurrentVariationMethod: Interpolated
  IncludeVesselWindLoads: true
  IncludeLineWindLoads: false
  IncludeBuoyWindLoads: true
  IncludeBuoyWingWindLoads: false
  WindRamping: From mean
  WindType: Constant
  AirDensity: 0.00128
  AirSpeedOfSound: 343
  VerticalWindVariationFactor: ~
  SeabedSlope: 0.0
  SeabedNormalStiffness: 100.0
  SeabedShearStiffness: 100.0
  Density: 1.025
  SeabedOriginDepth: 80.0
  WaveTrains:
  - Name: Wave 1
    WaveType: Dean stream
    WaveDirection: 120.0
    WaveHeight: 5.0
    WavePeriod: 13.0
    WaveOrigin:
    - 0
    - 0
    WaveTimeOrigin: 0
    WaveStreamFunctionOrder: 5
    WaveCurrentSpeedInWaveDirectionAtMeanWaterLevel: ~
  RefCurrentSpeed: 2.0
  RefCurrentDirection: 125.0
  CurrentDepth, CurrentFactor, CurrentRotation:
  - - 0.0
    - 1.0
    - 0
  - - 8.0
    - 1.0
    - 0
  - - 16.0
    - 1.0
    - 0
  - - 24.0
    - 0.8
    - 0
  - - 32.0
    - 0.5
    - 0
  WindSpeed: 0.0
  WindDirection: 210.0
