Environment:
  WaterSurfaceZ: 0
  KinematicViscosity: 1.35e-06
  SeaTemperature: 10
  ReynoldsNumberCalculation: Flow direction
  HorizontalWaterDensityFactor: ~
  VerticalDensityVariation: Constant
  SeabedType: Flat
  SeabedOrigin:
  - 0
  - 0
  NominalDepth: ~
  SeabedSlopeDirection: 0
  SeabedModel: Elastic
  WaveKinematicsCutoffDepth: Infinity
  WaveCalculationMethod: Instantaneous position (exact)
  WaveCalculationTimeInterval: 0
  WaveCalculationSpatialInterval: 0
  MultipleCurrentDataCanBeDefined: false
  CurrentModel: Variation scheme
  CurrentRamped: false
  CurrentApplyVerticalStretching: false
  HorizontalCurrentFactor: ~
  VerticalCurrentVariationMethod: Interpolated
  IncludeVesselWindLoads: true
  IncludeLineWindLoads: false
  IncludeBuoyWindLoads: true
  IncludeBuoyWingWindLoads: false
  WindRamping: From mean
  WindType: Constant
  AirDensity: 0.00128
  AirSpeedOfSound: 343
  VerticalWindVariationFactor: ~
  SeabedShearStiffness: 100.0
  SeabedSlope: 0.0
  SeabedNormalStiffness: 100.0
  KinematicStretchingMethod: Vertical stretching
  Density: 0.00128
  SeabedOriginDepth: 100.0
  WaveTrains:
  - Name: Wave1
    WaveType: Airy
    WaveDirection: 180.0
    WaveHeight: 0.0
    WavePeriod: 8.0
    WaveOrigin:
    - 0
    - 0
    WaveTimeOrigin: 0
  RefCurrentSpeed: 0.0
  RefCurrentDirection: 180.0
  CurrentDepth, CurrentFactor, CurrentRotation:
  - - 0.0
    - 1.0
    - 0
  - - 100.0
    - 0.9
    - 0
  WindSpeed: 1.0
  WindDirection: 180.0
