Analyze:
  - 16OD_SE1200_HE1500_100yr Wave, Far BeamSea PS.yml
  - 16OD_SE0500_HE0800_100yr Wave, Far BeamSea PS.yml
  - 16OD_SCR_100yr Wave, Far BeamSea PS.yml
  
PostProcess:
  - 
    PlotSettings: 
      Name: Static Analysis
      SupTitle: Frontier Deepwater Feasibility Analysis
      Title: SLWR Configuration Development Analysis
      SubTitle: 

    File: 
      - 
        Name: SLWR_16OD_SE1200_HE1500_100yr Wave, Far BeamSea PS.sim		
        Label: SLWR Configuration Far BeamSea PS, SE1200 
      - 
        Name: SLWR_16OD_SE0500_HE0800_100yr Wave, Far BeamSea PS.sim		
        Label: SLWR Configuration Far BeamSea PS, SE0500 Configuration
      -
        Name: SCR_16OD_SCR_100yr Wave, Far BeamSea PS.sim		
        Label: SCR Configuration, Far BeamSea PS Configuration
 
 
    Summary:
    #For object name SLWR
      -
        Command: Range Graph
        ObjectName: SLWR
        AdditionalData: 
          - Max
        SimulationPeriod: pnWholeSimulation
        ArcLength:
          - 0
          - 100
        Variable: Effective Tension
        xlabel: Arc Length (m)
        ylabel: Effective Tension (kN)
        suptitle: Effective Tension Response
        Label: Effective_Tension
      -
        Command: Range Graph
        ObjectName: SLWR
        AdditionalData: 
          - Max
        SimulationPeriod: pnWholeSimulation
        ArcLength:
          - 0
          - 100
        Variable: Bend Moment
        xlabel: Arc Length (m)
        ylabel: Bend Moment (kN.m)
        suptitle: Bending Moment Response
        Label: Bending_Moment
      -
        Command: Range Graph
        ObjectName: SLWR
        AdditionalData: 
          - Max
        SimulationPeriod: pnWholeSimulation
        ArcLength:
          - 0
          - 100
        Variable: Effective Tension
        xlabel: Arc Length (m)
        ylabel: Effective Tension (kN)
        suptitle: Effective Tension Response
        Label: Top_Effective_Tension
      -
        Command: Range Graph
        ObjectName: SLWR
        AdditionalData: 
          - Max
        SimulationPeriod: pnWholeSimulation
        ArcLength:
          - 0
          - 100
        Variable: Effective Tension
        xlabel: Arc Length (m)
        ylabel: Effective Tension (kN)
        suptitle: Effective Tension Response
        Label: SLWR_16OD_SE1200_HE1500_Effective_Tension_Top
      -
        Command: Range Graph
        ObjectName: SLWR
        AdditionalData: 
          - Max
        SimulationPeriod: pnWholeSimulation
        ArcLength:
          - 0
          - 100
        Variable: Max von Mises Stress
        xlabel: Arc Length (m)
        ylabel: Max von Mises Stress
        suptitle: Max von Mises Stress Response
        Label: Max von Mises Stress
        
      ## For ObjectName SCR
      -   
        Command: Range Graph
        ObjectName: SCR
        AdditionalData: 
          - Max
        SimulationPeriod: pnWholeSimulation
        ArcLength:
          - 0
          - 100
        Variable: Effective Tension
        xlabel: Arc Length (m)
        ylabel: Effective Tension (kN)
        suptitle: Effective Tension Response
        Label: Effective_Tension
      -
        Command: Range Graph
        ObjectName: SCR
        AdditionalData: 
          - Max
        SimulationPeriod: pnWholeSimulation
        ArcLength:
          - 0
          - 100
        Variable: Bend Moment
        xlabel: Arc Length (m)
        ylabel: Bend Moment (kN.m)
        suptitle: Bending Moment Response
        Label: Bending_Moment
      -
        Command: Range Graph
        ObjectName: SLWR
        AdditionalData: 
          - Max
        SimulationPeriod: pnWholeSimulation
        ArcLength:
          - 0
          - 100
        Variable: Effective Tension
        xlabel: Arc Length (m)
        ylabel: Effective Tension (kN)
        suptitle: Effective Tension Response
        Label: SLWR_16OD_SE1200_HE1500_Effective_Tension_Top
      -
        Command: Range Graph
        ObjectName: SCR
        AdditionalData: 
          - Max
        SimulationPeriod: pnWholeSimulation
        ArcLength:
          - 0
          - 100
        Variable: Max von Mises Stress
        xlabel: Arc Length (m)
        ylabel: Max von Mises Stress
        suptitle: Max von Mises Stress Response
        Label: Max von Mises Stress
        
    RangeGraph:
      #in range graph command, simulation period is WholeSimulation
      -
        Command: Range Graph
        ObjectName: SLWR
        AdditionalData: 
          - Max
        SimulationPeriod: pnWholeSimulation
        ArcLength:
        Variable: Effective Tension
        xlabel: Arc Length (m)
        ylabel: Effective Tension (kN)
        suptitle: Effective Tension Response
        FileName: 16OD_Configuration_Bending_Moment
      -
        Command: Range Graph
        ObjectName: SLWR
        AdditionalData: 
          - Max
        SimulationPeriod: pnWholeSimulation
        ArcLength:
        Variable: Bend Moment
        xlabel: Arc Length (m)
        ylabel: Bend Moment (kN.m)
        suptitle: Bending Moment Response
        FileName: 16OD_Configuration_Bending_Moment
      
      -
        Command: Range Graph
        ObjectName: SLWR
        AdditionalData: 
          - Max
        SimulationPeriod: pnWholeSimulation
        ArcLength:
          - 0
          - 100
        Variable: Max von Mises Stress
        xlabel: Arc Length (m)
        ylabel: Max von Mises Stress
        suptitle: Max von Mises Stress Response
        FileName: 16OD_Configuration_von Mises Stress
        
        ##for ObjectName SCR
      -
        Command: Range Graph
        ObjectName: SCR
        AdditionalData: 
          - Max
        SimulationPeriod: pnWholeSimulation
        ArcLength:
        Variable: Effective Tension
        xlabel: Arc Length (m)
        ylabel: Effective Tension (kN)
        suptitle: Effective Tension Response
        FileName: 16OD_Configuration_Bending_Moment
      -
        Command: Range Graph
        ObjectName: SCR
        AdditionalData: 
          - Max
        SimulationPeriod: pnWholeSimulation
        ArcLength:
        Variable: Bend Moment
        xlabel: Arc Length (m)
        ylabel: Bend Moment (kN.m)
        suptitle: Bending Moment Response
        FileName: 16OD_Configuration_Bending_Moment
      
      -
        Command: Range Graph
        ObjectName: SCR
        AdditionalData: 
          - Max
        SimulationPeriod: pnWholeSimulation
        Variable: Max von Mises Stress
        xlabel: Arc Length (m)
        ylabel: Max von Mises Stress
        suptitle: Max von Mises Stress Response
        FileName: 16OD_Configuration_von Mises Stress
      
      
    TimeHistory:
    ##in Time History command, simulation period is WholeSimulation
      -
        Command: Time History
        ObjectName: SLWR
        AdditionalData: 
          - End A
        SimulationPeriod: SpecifiedPeriod(30.0, 120.0)
        Variable: Effective Tension
      -
        Command: Time History
        ObjectName: SLWR
        AdditionalData: 
          - End A
        SimulationPeriod: SpecifiedPeriod(30.0, 120.0)
        Variable: Bend Moment
      -        
        Command: Time History
        ObjectName: SLWR
        AdditionalData: 
          - End A
        SimulationPeriod: SpecifiedPeriod(30.0, 120.0)
        Variable: Max von Mises Stress

        ## For ObjectName SCR
      -
        Command: Time History
        ObjectName: SCR
        AdditionalData: 
          - End A
        SimulationPeriod: SpecifiedPeriod(30.0, 120.0)
        Variable: Effective Tension
      -
        Command: Time History
        ObjectName: SCR
        AdditionalData: 
          - End A
        SimulationPeriod: SpecifiedPeriod(30.0, 120.0)
        Variable: Bend Moment
      -
        -
        Command: Time History
        ObjectName: SCR
        AdditionalData: 
          - End A
        SimulationPeriod: SpecifiedPeriod(30.0, 120.0)
        Variable: Max von Mises Stress